# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/ACADEMICS/Sem7/ADS/System_Bus_Zybo/System_Bus_Zybo.srcs/sources_1/ip/BRAM/BRAM.xci
# IP: The module: 'BRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ACADEMICS/Sem7/ADS/System_Bus_Zybo/System_Bus_Zybo.gen/sources_1/ip/BRAM/BRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/ACADEMICS/Sem7/ADS/System_Bus_Zybo/System_Bus_Zybo.srcs/sources_1/ip/BRAM/BRAM.xci
# IP: The module: 'BRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ACADEMICS/Sem7/ADS/System_Bus_Zybo/System_Bus_Zybo.gen/sources_1/ip/BRAM/BRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
